"use client";

import { Activity, AlertTriangle, ArrowUpRight, CheckCircle2, CircleAlert, Radar, ShieldCheck, Target } from "lucide-react";
import { useEffect, useState } from "react";
import riskData from "./riskData.json";
type Risk = (typeof riskData)[number];
const colorText = { red: "重大风险", orange: "较高风险", yellow: "关注风险", green: "低风险" } as const;
const score = (risk: Risk) => risk.probability * risk.impact;

export function RiskHeatmapExperience() {
  const [selected, setSelected] = useState<Risk>(riskData[1]); const [isReady, setIsReady] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => setIsReady(true), 180); return () => window.clearTimeout(timer); }, []);
  return <main className={`risk-page ${isReady ? "is-ready" : ""}`} data-header-theme="dark"><div className="risk-grain" /><div className="risk-grid-bg" />
    <section className="risk-hero"><div className="radar-kicker"><Radar size={16} /> FINANCE & TAX RISK INTELLIGENCE</div><div className="risk-hero-row"><div><h1>企业财税风险智能雷达</h1><p>基于经营数据、财务表现及税务规则，<br />识别企业潜在涉税风险。</p></div><div className="demo-state"><span>DEMO MODE</span><small>模拟扫描结果，仅用于服务展示</small></div></div><div className="risk-metrics">{[["128", "风险扫描项目", <Target key="t" />], ["11", "发现风险", <CircleAlert key="c" />], ["2", "重大风险", <AlertTriangle key="a" />], ["78", "综合风险指数", <Activity key="ac" />]].map(([value, label, icon], i) => <article className={`metric metric-${i}`} key={label as string}><span>{icon}</span><strong>{value}{i === 3 && <em> / 100</em>}</strong><small>{label}</small></article>)}</div></section>
    <section className="risk-main-grid"><article className="risk-matrix-panel"><div className="panel-heading"><div><p>RISK DISTRIBUTION / 01</p><h2>风险热力矩阵</h2></div><div className="legend">{Object.entries(colorText).map(([color, text]) => <span key={color}><i className={color} />{text}</span>)}</div></div><div className="matrix-layout"><div className="impact-axis"><b>损失影响程度</b><span>重大影响</span><span>中等影响</span><span>轻微影响</span></div><div className="matrix-block"><div className="matrix-scan" /><div className="matrix-corners"><span>高</span><span>发生可能性 →</span></div><div className="matrix-cells">{Array.from({ length: 25 }, (_, index) => <i key={index} className={`zone cell-${Math.floor(index / 5)}-${index % 5}`} />)}</div>{riskData.map((risk, index) => <button key={risk.name} onClick={() => setSelected(risk)} aria-label={`查看${risk.name}详情`} className={`risk-bubble ${risk.color} ${selected.name === risk.name ? "selected" : ""}`} style={{ left: `${(risk.probability - 1) * 25 + 12.5 + ((index % 3) - 1) * 3}%`, top: `${(5 - risk.impact) * 20 + 10 + ((index % 2) * 5 - 2.5)}%`, "--delay": `${index * 80}ms`, "--size": `${34 + score(risk) * 1.8}px` } as React.CSSProperties}><span>{risk.name.slice(0, 2)}</span></button>)}<div className="probability-axis"><span>低概率</span><span>较低</span><span>中等</span><span>较高</span><span>高概率</span></div></div></div><div className="matrix-caption"><span><Target size={15} /> 点击风险气泡，查看顾问诊断建议</span><span>动态扫描中 <i /></span></div></article>
      <aside className="risk-detail-panel"><div className="detail-status"><span><i /> 已锁定风险点</span><small>RISK ID · {String(riskData.indexOf(selected) + 1).padStart(3, "0")}</small></div><div className="detail-title"><div className={`risk-icon ${selected.color}`}><ShieldCheck size={22} /></div><div><p>风险名称</p><h2>{selected.name}</h2></div></div><div className="risk-level"><span>风险等级</span><strong className={selected.color}>{selected.level}风险</strong><b>{colorText[selected.color as keyof typeof colorText]}</b></div><div className="risk-readings"><div><small>发生概率</small><strong>{selected.probability}<em>/5</em></strong><i><b style={{ width: `${selected.probability * 20}%` }} /></i></div><div><small>影响程度</small><strong>{selected.impact}<em>/5</em></strong><i><b style={{ width: `${selected.impact * 20}%` }} /></i></div></div><section className="detail-section"><p>可能后果</p><ul>{selected.consequences.map((item, index) => <li key={item}><b>{index + 1}</b>{item}</li>)}</ul></section><section className="advice"><p><CheckCircle2 size={15} /> 顾问建议</p><strong>{selected.advice}</strong></section><div className="detail-footer"><span>风险说明：{selected.description}</span><button>获取专属体检方案 <ArrowUpRight size={15} /></button></div></aside></section>
    <section className="risk-bottom"><div><p>PROFESSIONAL SCAN / 02</p><h2>不是罗列风险，而是看清风险的优先级。</h2></div><p>将业务、财务、税务与内控信号放进同一张图，让企业管理者清晰看见：什么必须立即处理，什么可以系统性改善。</p></section></main>;
}
